CREATE DATABASE IF NOT EXISTS recommand_workspace;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_shop_base_third(
    Id BIGINT,
    Str_Id VARCHAR(64),
    Mer_Id VARCHAR(64),
    Str_Nm VARCHAR(128),
    City_Cd VARCHAR(32),
    City_Nm VARCHAR(32),
    Cnty_Cd VARCHAR(32),
    Cnty_Nm VARCHAR(32),
    Addr VARCHAR(256),
    Lng VARCHAR(20),
    Lat VARCHAR(20),
    Cat_Id VARCHAR(512),
    Cat_Nm VARCHAR(512),
    Avg_Prc VARCHAR(10),
    str_lVl VARCHAR(4),
    Srvc_Tag VARCHAR(128),
    Str_Logo_Path VARCHAR(512),
    obj_Jmp_Lnk VARCHAR(512),
    Str_Quality_Type INT,
    Str_Mall_Id_Md5 VARCHAR(128),
    Str_Mall_Nm VARCHAR(512),
    Remark VARCHAR(512),
    Bch_Sn BIGINT,
    Chk_St VARCHAR(12),
    Str_Type VARCHAR(10),
    str_Meituan_Sta INT,
    str_Sta VARCHAR(12),
    Admi_Flag BOOLEAN,
    Mnt_Pern_Usr_Num VARCHAR(32),
    Pre_Flag BOOLEAN,
    Crt_Psn_Id VARCHAR(32),
    Updt_Psn_Id VARCHAR(32),
    Crt_Dt_tm TIMESTAMP,
    Updt_Dt_Tm TIMESTAMP,
    Cat_Id_NEW BIGINT
) PARTITIONED BY (`etl_dt` STRING COMMENT '分区日期:[yyyyMMdd]') ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_shop_category_mapping(
    Id BIGINT,
    Prnt_Id BIGINT,
    Cat_Nm VARCHAR(32),
    sortNo INT,
    Cat_Sta VARCHAR(5),
    Std_Lv1 INT,
    mt_cat_ids VARCHAR(255),
    se1f_cat_ids VARCHAR(255),
    Crt_Psn_Id VARCHAR(32),
    Updt_Psn_Id VARCHAR(32),
    Crt_Dt_Tm TIMESTAMP,
    Updt_Dt_Tm TIMESTAMP
) PARTITIONED BY (`etl_dt` STRING COMMENT '分区日期:[yyyyMMdd]') ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_shop_category_meituan(
    Id BIGINT,
    Cat_Id BIGINT,
    Prnt_Id BIGINT,
    Cat_Nm VARCHAR(32),
    Cat_Sta VARCHAR(5),
    Std_Lv1 INT,
    Crt_Psn_Id VARCHAR(32),
    Updt_Psn_Id VARCHAR(32),
    Crt_DT_Tm TIMESTAMP,
    Updt_Dt_Tm TIMESTAMP
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.CDM_ADM_CUST_INFO_STAT_F(
    ETL_DATE VARCHAR(8),
    PROCESSED_DATE VARCHAR(19),
    MASTERCARD_CUST_ID VARCHAR(19),
    BRANCH_ID BIGINT,
    PRODUCT_ID BIGINT,
    CUST_OPEN_DT VARCHAR(8),
    BIRTH_DT VARCHAR(8),
    EDUCATION_ID BIGINT,
    SEX_ID BIGINT,
    MARRIAGE_ID BIGINT,
    SELF_INCOME DECIMAL(12, 2),
    CRLIMIT_RMB DECIMAL(12, 2),
    CRLIMIT_USD DECIMAL(12, 2),
    CC_ID BIGINT,
    OC_ID BIGINT,
    PC_ID BIGINT,
    OFFICE_TEL VARCHAR(17),
    CLASS_CD VARCHAR(3),
    COMP_NM VARCHAR(30),
    RELATE1_NM VARCHAR(30),
    RELATE2_NM VARCHAR(30),
    RELATE1_TEL VARCHAR(17),
    RELATE2_TEL VARCHAR(17),
    RELATE1_COMP_NM VARCHAR(30),
    RELATE1_RELATION VARCHAR(4),
    RELATE2_COMP_NM VARCHAR(30),
    RELATE2_RELATION VARCHAR(4),
    EMAIL_ADDR VARCHAR(40),
    COMP_DEPART VARCHAR(30),
    TEL_BRANCH VARCHAR(6),
    RESIDENT_FLG VARCHAR(1),
    HOME_TEL VARCHAR(17),
    CON_INCOME DECIMAL(12, 2),
    MOBILE_NMBR VARCHAR(12),
    MP_LIMIT DECIMAL(12, 2),
    EN_NM VARCHAR(30),
    COMP_TYPE VARCHAR(2),
    DUTY VARCHAR(30),
    ID_TYPE VARCHAR(2),
    NAME VARCHAR(30),
    NAME_TITLE VARCHAR(30),
    RELATION_FLG VARCHAR(1),
    SELF_WORDYEAR BIGINT,
    RESIDENT_YEAR BIGINT,
    HOME_LOAN_MONTH_AMT BIGINT,
    RELATE1_MOBILE VARCHAR(12),
    RELATE2_MOBILE VARCHAR(12),
    VALUE_LEVEL VARCHAR(1),
    RISK_LEVEL VARCHAR(2),
    TEL_YN VARCHAR(1),
    MOBILE_YN VARCHAR(1),
    SMS_YN VARCHAR(1),
    EMAIL_YN VARCHAR(1),
    LETTER_YN VARCHAR(1),
    CREDADJUST_FLG VARCHAR(1),
    CASH_RATE DECIMAL(5, 2),
    CUSTREF_NO VARCHAR(19),
    CUSTAPP_TYPE VARCHAR(2),
    YEAR_EARN DECIMAL(12, 2),
    SAVINGSUM DECIMAL(12, 2),
    NSA_VALUE DECIMAL(12, 2),
    HP_VALUE DECIMAL(12, 2),
    CAR_VALUE DECIMAL(12, 2),
    BNK_RPT VARCHAR(1),
    CREDADJUSTTEMP_IND VARCHAR(1),
    TRANS_TYPE VARCHAR(2),
    IMP_FLAG VARCHAR(1),
    PER_SCORE BIGINT,
    NPERS_RSN VARCHAR(20),
    SECUR_NO VARCHAR(18),
    NATION_CODE VARCHAR(1),
    CAR_DATE VARCHAR(8),
    CAR_ID VARCHAR(10),
    CAR_NAME VARCHAR(16),
    CAR_CODE VARCHAR(1),
    FAMILY_RELATION VARCHAR(4),
    CON_COMP_NAME VARCHAR(30),
    CON_ID_NO VARCHAR(19),
    DEPENDENTS_NUM BIGINT,
    CON_INCOME_SOURCE VARCHAR(1),
    SELF_INCOME_SOURCE VARCHAR(1),
    FAX_CODE VARCHAR(17),
    LANGUAGE_CODE VARCHAR(2),
    AD_TYPE VARCHAR(2),
    FAMILY_NAME VARCHAR(30),
    FAMILY_TEL VARCHAR(17),
    PRIORCOMP_DUTY VARCHAR(2),
    PRIORCOMP_INCOME DECIMAL(12, 2),
    PRIORCOMP_YEAR BIGINT,
    CON_NAME VARCHAR(30),
    CON_TEL VARCHAR(17),
    CON_WORKYEAR BIGINT,
    CON_MOBILE VARCHAR(12),
    FAMILY_RELATE_MOBILE VARCHAR(12),
    INT_TAXCOD VARCHAR(2),
    ID_VERIFY VARCHAR(1),
    IDCP_YN VARCHAR(1),
    CUST_FLAG VARCHAR(1),
    VALID_CUST_FLG VARCHAR(1),
    CURRENCE_CUST_FLG VARCHAR(1),
    LIVE_CUST_FLG VARCHAR(1),
    REGULAR_CUST_FLG VARCHAR(1),
    CUST_ORIGINAL_CRLIMIT DECIMAL(12, 2),
    VALID_MOBILE_NMBR VARCHAR(1),
    VALID_EMAIL_ADDR VARCHAR(1),
    RACT_CUST_FLG VARCHAR(1),
    CUST_MAX_LEVEL VARCHAR(10),
    INIT_CANCEL_FLG VARCHAR(1),
    PRIORCOMP_NM VARCHAR(30),
    PRIORCOMP_DEPT VARCHAR(20),
    PRIORCOMP_TEL VARCHAR(17),
    STUDENT_FLG VARCHAR(1),
    STU_GRADE BIGINT,
    EMPLOYEE_ID VARCHAR(6),
    SP_CUSTR1 VARCHAR(4),
    SP_CUSTR2 VARCHAR(4),
    SP_CUSTR3 VARCHAR(4),
    SP_CUSTR4 VARCHAR(4),
    SP_CUSTR5 VARCHAR(4),
    REDUCE_YN VARCHAR(1),
    OCT_SCORE BIGINT,
    CYCLE_CUST_FLG VARCHAR(1),
    CSH_CUST_FLG VARCHAR(1),
    MP_CUST_FLG VARCHAR(1),
    CUST_FC VARCHAR(20),
    LMP_LIMIT BIGINT,
    LMPF_LIMIT BIGINT,
    LMPZ_EXPDT VARCHAR(8),
    LCAL_EXPDT VARCHAR(8),
    LDL_EXPDT VARCHAR(8),
    CIFNAME VARCHAR(60),
    NATION_DET VARCHAR(20),
    ID_DTE VARCHAR(8),
    IDLT_YN BIGINT,
    RISK_LEVEL_XQ VARCHAR(1),
    IS_FOREIGN_TRANS_FLAG VARCHAR(1),
    IS_TRA_TRANS_FLAG VARCHAR(1),
    IS_TRA_FOREIGN_TRANS_FLAG VARCHAR(1),
    IS_TRA_INTERIN_TRANS_FLAG VARCHAR(1),
    IS_PUR_TRANS_FLAG VARCHAR(1),
    IS_UPGRADE_CUST VARCHAR(1),
    IS_AUTOKEAP_CUST VARCHAR(1),
    IS_BORROW_CUST VARCHAR(1),
    IS_KSFK_ACTIVE_CUST VARCHAR(1),
    CUST_LIMIT_SQ DECIMAL(12, 2),
    CUST_LIMIT_HDZ DECIMAL(12, 2),
    CUST_LIMIT_HFZD DECIMAL(12, 2),
    CUST_DELQ_ID BIGINT,
    CUST_CREDIT_PPL DECIMAL(12, 2),
    UNUSED_CRLIMIT DECIMAL(12, 2),
    ASSET_FIVE_CATEGORY VARCHAR(8),
    OCC_CODE VARCHAR(4),
    BRNCH_ADJ BIGINT,
    IS_XYT_CUST VARCHAR(1),
    CUST_CREDIT_LIMIT DECIMAL(12, 2),
    GRC_FLAG VARCHAR(1),
    CUST_CREDLMT_NOTMP DECIMAL(12, 2),
    CUST_IMP_LIMIT DECIMAL(12, 2),
    FIVETIER_CLS_SRC_HQ_RISK VARCHAR(1),
    OD_PRIN_SRC_HQ_RISK DECIMAL(15, 2),
    NP_AMT DECIMAL(15, 2),
    CUST_OVDUE_OD_PRIN DECIMAL(15, 2),
    M1_ENT_COUNT DECIMAL(15, 2),
    M2_ENT_COUNT DECIMAL(15, 2),
    M3_ENT_COUNT DECIMAL(15, 2),
    M4_ENT_COUNT DECIMAL(15, 2),
    M1_PRINCIPAL_SUM DECIMAL(15, 2),
    M2_PRINCIPAL_SUM DECIMAL(15, 2),
    M3_PRINCIPAL_SUM DECIMAL(15, 2),
    M4_PRINCIPAL_SUM DECIMAL(15, 2),
    ZFB_FLG VARCHAR(1),
    WX_FLG VARCHAR(1),
    QUICK_PAY_FLG VARCHAR(1),
    FIX_LMT_FLG VARCHAR(1),
    AC02_ACCT_VALUE DECIMAL(13, 2),
    JD_FLG VARCHAR(1),
    PDD_FLG VARCHAR(1),
    MT_FLG VARCHAR(1),
    DY_FLG VARCHAR(1),
    XC_FLG VARCHAR(1),
    ESELL_SPME_LOAN_TM VARCHAR(1),
    LATST_BASE_EQTY_CUM_PRMTN_TM VARCHAR(8),
    EQTY_PRMTN_CUST_FLG VARCHAR(1),
    SELF_DED_REPAY_CUST_FLG VARCHAR(1),
    CTRL_CRDT_AMT DECIMAL(12, 2),
    ALIPAY_TRAN_FLG VARCHAR(1),
    TENPAY_TRAN_FLG VARCHAR(1),
    UPCQP_TRAN_FLG VARCHAR(1),
    VALID_ACCT_SLEEP_M6_IDNT VARCHAR(1),
    ONLINE_RACT_CUST_FLG VARCHAR(1),
    DD_FLG VARCHAR(1),
    WPH_FLG VARCHAR(1)
) PARTITIONED BY (`etl_dt` STRING COMMENT '分区日期:[yyyyMMdd]') ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_shop_base(
    shopId VARCHAR(64),
    merchantId VARCHAR(64),
    shopName VARCHAR(100),
    shopAbbr VARCHAR(32),
    shopStatus VARCHAR(12),
    shopLogoPath VARCHAR(100),
    catId BIGINT,
    bizAreaId BIGINT,
    bussinessWeeks VARCHAR(7),
    bussiStartTime STRING,
    bussiEndTime STRING,
    shopServicePhone VARCHAR(64),
    isSyncConName VARCHAR(4),
    shopContactName VARCHAR(20),
    isSyncConTel VARCHAR(4),
    shopContactTel VARCHAR(16),
    isSyncMechtSettle VARCHAR(4),
    isOpenonline VARCHAR(4),
    onlineShopNo VARCHAR(64),
    isSignOnlinePay VARCHAR(4),
    isMultCpnVerity VARCHAR(4),
    createTime TIMESTAMP,
    lastUpdatelime TIMESTAMP,
    syncMerClerkNo VARCHAR(4),
    clerkNo VARCHAR(32),
    mccId BIGINT,
    auditStatus VARCHAR(12),
    distance VARCHAR(32),
    orgIds VARCHAR(64),
    shopManagerLoginNum VARCHAR(64),
    update_time TIMESTAMP,
    create_time TIMESTAMP,
    hitScene VARCHAR(20),
    sourceCode VARCHAR(4),
    shopType VARCHAR(6),
    brandId BIGINT,
    Brnd_Nm VARCHAR(80),
    Opr_Psn_Id VARCHAR(32),
    Wht_Atch VARCHAR(4),
    Fir_Lv_Inst_Id BIGINT,
    Sec_Lv_Inst_Id BIGINT,
    Thi_Lv_Inst_Id BIGINT,
    Mnt_Pern_Usr_Num VARCHAR(32),
    Cat_Id_NEW BIGINT
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_shop_address(
    Id BIGINT,
    shopId VARCHAR(64),
    provinceId BIGINT,
    cityId BIGINT,
    areaId BIGINT,
    detailAddr VARCHAR(600),
    longitude VARCHAR(20),
    latitude VARCHAR(20),
    createTime TIMESTAMP,
    updateTime TIMESTAMP,
    create_time TIMESTAMP,
    update_time TIMESTAMP
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_shop_category(
    catId BIGINT,
    parentId BIGINT,
    catName VARCHAR(32),
    sortNo INT,
    catStatus VARCHAR(5),
    level INT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_coupon_template(
    couponId BIGINT,
    couponCoreId VARCHAR(50),
    coopBatchNo VARCHAR(50),
    producerType VARCHAR(6),
    verifyWay VARCHAR(16),
    outerDisPlayRule VARCHAR(10),
    dispalyOuter VARCHAR(4),
    outerUrl VARCHAR(255),
    couponType VARCHAR(10),
    overlayPay VARCHAR(4),
    overlayDiscountPay VARCHAR(4),
    achieveType VARCHAR(6),
    facePrice DECIMAL(10, 2),
    currentPrice DECIMAL(10, 2),
    couponName VARCHAR(100),
    unbindCardLimit INT,
    bindCardLimit INT,
    allowPresent VARCHAR(4),
    ruleDescription VARCHAR(4096),
    primaryImgUrl VARCHAR(100),
    useScopeAbbre VARCHAR(255),
    buttonStyle VARCHAR(10),
    mktAdsType VARCHAR(6),
    mktAdsInitValue INT,
    subscript VARCHAR(4),
    subscriptType VARCHAR(6),
    subscriptDesc VARCHAR(64),
    displayProductDesc VARCHAR(4),
    productDesc VARCHAR(4096),
    subsidyActId VARCHAR(64),
    settleWay VARCHAR(10),
    subsidySettleWay VARCHAR(5),
    bankSubsidyAmt DECIMAL(15, 2),
    branchSubsidyAmt DECIMAL(15, 2),
    mchtSubsidyAmt DECIMAL(15, 2),
    couponstatus VARCHAR(10),
    firstBankOrg BIGINT,
    secondBankOrg BIGINT,
    thridBankOrg BIGINT,
    achieveRule VARCHAR(10),
    achieveActId VARCHAR(50),
    createTime TIMESTAMP,
    lastUpdateTime TIMESTAMP,
    creator VARCHAR(50),
    updatePerson VARCHAR(50),
    displayStatus VARCHAR(16),
    cpnMdlId VARCHAR(64),
    couponSource VARCHAR(10),
    orgId VARCHAR(64),
    maxEffectTime TIMESTAMP,
    suitDimen VARCHAR(6),
    setBindCardLimit SMALLINT,
    setUnBindCardLimit SMALLINT,
    shopMoreOne VARCHAR(4),
    productDescType VARCHAR(16),
    merShopUrl VARCHAR(256),
    merShopImportType VARCHAR(16),
    mgmActivityId VARCHAR(64),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    isAnyShop VARCHAR(4),
    isAnyMerchant VARCHAR(4),
    isAnyOrg VARCHAR(4),
    sourceCode VARCHAR(4),
    firstOutType INT,
    secondOutType INT,
    activityTitle INT,
    buyMethod VARCHAR(20),
    pointCnsmNum BIGINT,
    defultRemark VARCHAR(2048),
    uniqueCpn VARCHAR(50),
    limitType VARCHAR(50),
    mixedType VARCHAR(64),
    startTime TIMESTAMP,
    endTime TIMESTAMP,
    onlinePayThreshold DECIMAL(15, 2),
    refundRule VARCHAR(255),
    isExpireAlarm VARCHAR(6)
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_discounts_pay(
    discountsPayId BIGINT,
    discountsPayName VARCHAR(100),
    discountsPayState VARCHAR(10),
    displayState VARCHAR(10),
    setLimitNum VARCHAR(4),
    maxDiscountsNum INT,
    payWay VARCHAR(100),
    discountsRule VARCHAR(10),
    discountsReduceValue VARCHAR(100),
    setLimitAmt VARCHAR(4),
    maxDiscountsAmt DECIMAL(15, 2),
    SettleWay VARCHAR(10),
    subsidySettleWay VARCHAR(5),
    apportionRuleValue VARCHAR(100),
    actBudgetId VARCHAR(50),
    orgIds VARCHAR(64),
    createTime STRING,
    creatorId VARCHAR(20),
    creatorName VARCHAR(50),
    lastUpdateTime TIMESTAMP,
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    isAnyshop VARCHAR(4),
    isAnyMerchant VARCHAR(4),
    isAnyOrg VARCHAR(4),
    discountDescribe VARCHAR(4096)
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS recommand_workspace.o2o_new_gut_coupon_shop(
    id BIGINT,
    couponId BIGINT,
    suitType VARCHAR(5),
    suitAttrName VARCHAR(100),
    suitAttrId VARCHAR(64),
    merchantId VARCHAR(64),
    createTime STRING,
    batchNo VARCHAR(64),
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    merchantName VARCHAR(64),
    firstOrgId BIGINT,
    secondorgId BIGINT,
    thirdOrgId BIGINT
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE;

CREATE DATABASE IF NOT EXISTS cdm;

CREATE TABLE IF NOT EXISTS cdm.c10_ods_events_xysh (
    `event` STRING COMMENT '事件名称',
    `user_id` STRING COMMENT '神策用户ID',
    `day` STRING COMMENT '1970.1.1到现在间隔多少天',
    `event_id` STRING COMMENT '神策保留字段，事件id',
    `month_id` STRING COMMENT '1970.1.1到现在间隔多少月',
    `week_id` STRING COMMENT '1970.1.1到现在间隔多少周',
    `distinct_id` STRING COMMENT '用户ID',
    `date` STRING COMMENT '日期',
    `time` STRING COMMENT '时间',
    `app_version` STRING COMMENT '应用版本',
    `is_first_day` STRING COMMENT '是否首日访问',
    `latitude` STRING COMMENT '纬度',
    `longitude` STRING COMMENT '经度',
    `url` STRING COMMENT '页面地址',
    `bot_name` STRING COMMENT '爬虫名称',
    `receive_time` STRING COMMENT '服务端收到整个消息的时间',
    `manufacturer` STRING COMMENT '设备制造商',
    `model` STRING COMMENT '设备型号',
    `os` STRING COMMENT '操作系统',
    `os_version` STRING COMMENT '操作系统版本',
    `screen_height` STRING COMMENT '屏幕高度',
    `screen_width` STRING COMMENT '屏幕宽度',
    `wifi` STRING COMMENT '是否WIFI',
    `carrier` STRING COMMENT '运营商',
    `network_type` STRING COMMENT '网络类型',
    `device_id` STRING COMMENT '设备ID',
    `screen_orientation` STRING COMMENT '屏幕方向',
    `browser` STRING COMMENT '浏览器',
    `browser_version` STRING COMMENT '浏览器版本',
    `lib` STRING COMMENT 'SDK类型',
    `lib_version` STRING COMMENT 'SDK版本',
    `lib_method` STRING COMMENT '埋点方式',
    `ip` STRING COMMENT 'IP',
    `country` STRING COMMENT '国家',
    `city` STRING COMMENT '城市',
    `province` STRING COMMENT '省份',
    `app_id` STRING COMMENT '应用唯一标识',
    `app_name` STRING COMMENT '应用名称',
    `brand` STRING COMMENT '设备品牌',
    `event_duration` STRING COMMENT '事件时长',
    `idmap_reason` STRING COMMENT 'ID关联原因',
    `is_first_time` STRING COMMENT '是否首次触发事件',
    `is_login_id` STRING COMMENT '是否登录ID',
    `lib_plugin_version` STRING COMMENT 'SDK插件版本号',
    `resume_from_background` STRING COMMENT '是否从后台唤醒',
    `sf_plan_id` STRING COMMENT '运营计划ID',
    `sf_plan_type` STRING COMMENT '计划类型',
    `sf_plan_id_virtual` STRING COMMENT '计划名称',
    `sf_fail_reason` STRING COMMENT '消息发送失败原因',
    `sf_succeed` STRING COMMENT '消息发送成功',
    `timezone_offset` STRING COMMENT '时区偏移量',
    `sys_nm` STRING COMMENT '系统名称',
    `trd_sys_id` STRING COMMENT '系统编号',
    `sys_abbr` STRING COMMENT '系统简称',
    `cust_id` STRING COMMENT '客户编号（CIF号）',
    `unt_usr_id` STRING COMMENT '统一用户ID',
    `brc_nm` STRING COMMENT '分行名称',
    `rtl_cust_lv` STRING COMMENT '零售客户层级',
    `evnt_trk_plfm` STRING COMMENT '应用点平台名称',
    `mp_em` STRING COMMENT '小程序英文名称',
    `sml_prgrm_nm` STRING COMMENT '小程序名称',
    `usr_lgn_st` STRING COMMENT '用户登录状态',
    `trck_id` STRING COMMENT '埋点跟踪编号',
    `cpt_trk_id` STRING COMMENT '组件化埋点追踪ID',
    `cpt_spm_b` STRING COMMENT '组件化B位名称',
    `cpt_src_sys_nm` STRING COMMENT '组件来源系统简称',
    `mny_mgr_usr_id` STRING COMMENT '钱大掌柜用户编号',
    `cib_lf_usr_id` STRING COMMENT '兴业生活用户编号',
    `bnk_plfm_usr_id` STRING COMMENT '银银平台用户编号',
    `lgn_md` STRING COMMENT '登录方式',
    `hskpr_usr_id` STRING COMMENT '兴业管家用户编号',
    `fin_enty_cust_id` STRING COMMENT '金融机构客户号',
    `dvc_unq_num` STRING COMMENT '设备唯一编码',
    `vrsn_tp` STRING COMMENT '版本类型',
    `everyuser_no` STRING COMMENT '兴业普惠用户编号',
    `pg_src_sys_id` STRING COMMENT '页面来源系统编号',
    `req_id` STRING COMMENT '需求标识',
    `ebnk_elec_chnl_cd` STRING COMMENT '网银电子渠道码',
    `entp_ebnk_usr_typ` STRING COMMENT '企业网银用户类型',
    `entp_fin_unt_ctf_lgn_nm` STRING COMMENT '企金统一认证登录名',
    `pak_id` STRING COMMENT '园区号',
    `prk_tnt_id` STRING COMMENT '园区租户编号',
    `euipid` STRING COMMENT '统一用户身份编号',
    `ent_nm` STRING COMMENT '企业名称',
    `ker_cif_id` STRING COMMENT '核心客户号',
    `emp_id` STRING COMMENT '人力编号',
    `sx_cd` STRING COMMENT '性别代码',
    `ag` STRING COMMENT '年龄',
    `mkt_cmp_id` STRING COMMENT '营销活动编号',
    `agt_cust_flg` STRING COMMENT '代表客户标志',
    `opn_dt` STRING COMMENT '开户日期',
    `lst_s_appl_tm` STRING COMMENT '上次启动应用时间',
    `occ_cd` STRING COMMENT '职业代码',
    `lst_lgn_appl_tm` STRING COMMENT '上次登录应用时间',
    `inst_nm` STRING COMMENT '机构名称',
    `inst_id` STRING COMMENT '机构编号',
    `inst_typ` STRING COMMENT '机构类型',
    `lgh_appl_usr_id` STRING COMMENT '轻应用用户编号',
    `lgh_appl_union_id` STRING COMMENT '轻应用用户联合标识符',
    `notesid` STRING COMMENT 'NOTES号',
    `usr_certf_patt` STRING COMMENT '用户认证模式',
    `sec_lvl_inst_nm` STRING COMMENT '二级机构名称',
    `req_inst` STRING COMMENT '需求提出机构',
    `req_notesid` STRING COMMENT '需求提出人Notes号',
    `spm_a` STRING COMMENT 'A位名称',
    `spm_b` STRING COMMENT 'B位名称',
    `spm_c` STRING COMMENT 'C位名称',
    `spm_d` STRING COMMENT 'D位名称',
    `pg_type` STRING COMMENT '页面类型名称',
    `sec_pg_type` STRING COMMENT '页面类型二级分类名称',
    `func_mdl` STRING COMMENT '功能名称（A位）',
    `func_mn` STRING COMMENT '功能菜单（小A）',
    `func_key` STRING COMMENT '功能模块配置码',
    `func_key_nm` STRING COMMENT '功能模块配置码中文名称',
    `dt_src` STRING COMMENT '流量来源（外部）',
    `intl_dt_src` STRING COMMENT '内部流量来源',
    `cls_info` STRING COMMENT '曝光内容',
    `cls_rank` STRING COMMENT '排序',
    `cls_typ` STRING COMMENT '曝光类型',
    `cls_url` STRING COMMENT '曝光链接',
    `prd_cd` STRING COMMENT '金融产品编号',
    `prd_nm` STRING COMMENT '产品名称',
    `prd_typ` STRING COMMENT '产品类型',
    `pg_url` STRING COMMENT '页面地址',
    `pg_nm` STRING COMMENT '页面名称',
    `pg_cd` STRING COMMENT '页面编码',
    `pg_refer` STRING COMMENT '前向页面地址',
    `pg_refer_nm` STRING COMMENT '前向页面名称',
    `pg_refer_cd` STRING COMMENT '前向页面流水号',
    `bf_rwd_pg_addr` STRING COMMENT '前前向页面地址',
    `bf_rwd_pg_nm` STRING COMMENT '前前向页面名称',
    `obj_jmp_lnk` STRING COMMENT '目标跳转链接',
    `pic_lnk` STRING COMMENT '图片链接',
    `btn_nm` STRING COMMENT '按钮名称',
    `fl_cnt` STRING COMMENT '填写内容',
    `cur` STRING COMMENT '币种',
    `cur_unt` STRING COMMENT '货币单位',
    `lng_typ` STRING COMMENT '语言种类',
    `call_amt` STRING COMMENT '赎回金额',
    `dsnt_rdm_md` STRING COMMENT '赎回方式',
    `inp_amt` STRING COMMENT '输入金额',
    `inp_shr` STRING COMMENT '输入份额',
    `loc_dt` STRING COMMENT '日期选择',
    `cust_rsk_rnk` STRING COMMENT '风险等级',
    `trm_des` STRING COMMENT '期限',
    `msg_psh_num` STRING COMMENT '消息推送编码',
    `msg_psh_info` STRING COMMENT '消息推送信息',
    `msg_psh_cls_nm` STRING COMMENT '消息推送种类',
    `shr_chnl_nm` STRING COMMENT '渠道',
    `usr_coll_flg` STRING COMMENT '收藏',
    `cntrpty_bnk_nm` STRING COMMENT '交易银行名称',
    `fin_rcmnr_fil_nm` STRING COMMENT '推荐人',
    `bck_wrd` STRING COMMENT '底纹词',
    `pg_cfm_amt` STRING COMMENT '购买确认金额',
    `pct_yld` STRING COMMENT '收益率',
    `int_rt` STRING COMMENT '利率',
    `cntnt_lbl` STRING COMMENT '内容标签',
    `annc_ttl` STRING COMMENT '公告标题',
    `fdbk_opi` STRING COMMENT '反馈意见',
    `rmrk_info` STRING COMMENT '备注信息',
    `cust_acc_typ` STRING COMMENT '客户账户类型',
    `rsk_ctrl_dev_fingprt_id` STRING COMMENT '风控设备指纹内码',
    `mac_addr` STRING COMMENT 'Mac地址',
    `ply_bill_nm` STRING COMMENT '海报名称',
    `emp_fll_nm` STRING COMMENT '人力ID的姓名',
    `fdbk_rst` STRING COMMENT '反馈结果',
    `lic_plt_num` STRING COMMENT '车牌号',
    `veh_typ` STRING COMMENT '车型型号',
    `bind_veh_tm` STRING COMMENT '绑车时间',
    `int_sys_id` STRING COMMENT '交互系统编号',
    `ann_int_rt` STRING COMMENT '年化利率',
    `cont_mrk` STRING COMMENT '续存标记',
    `opr_dt` STRING COMMENT '操作日期',
    `lv_expd_num_d` STRING COMMENT '剩余到期天数',
    `ln_usg_cd` STRING COMMENT '贷款用途代码',
    `disb_rsn_fr_fal` STRING COMMENT '放款失败原因',
    `cib_cd_cat` STRING COMMENT '兴业卡类别',
    `ctf_typ` STRING COMMENT '证件类型',
    `cdt_cd_mn_sub_cd_ind` STRING COMMENT '是否主附卡',
    `cdt_cd_ist_trm` STRING COMMENT '信用卡分期期数',
    `cdt_cd_ist_comm_fee_col_md` STRING COMMENT '信用卡分期手续费收取方式',
    `wc_cust_id` STRING COMMENT '微信客户编号',
    `tran_shr` STRING COMMENT '份额',
    `cust_cur_id` STRING COMMENT '客户当前身份',
    `flw_nm` STRING COMMENT '业务流程',
    `aset_dstrn_pct` STRING COMMENT '资产分配比例',
    `pstr_id` STRING COMMENT '海报id',
    `shr_cntnt_id` STRING COMMENT '分享Id',
    `shr_md` STRING COMMENT '分享方式',
    `call_intf_nm` STRING COMMENT '调用接口名称',
    `encrp_md` STRING COMMENT '加密方式',
    `sct_txt_cntnt` STRING COMMENT '秘文内容',
    `cap_flw_md` STRING COMMENT '资金流转方式',
    `prj_num` STRING COMMENT '关联项目号',
    `scrty_instr_certf_sn` STRING COMMENT '安全工具证书序号',
    `scrty_instr_certf_manuf` STRING COMMENT '安全工具证书厂商',
    `scrty_certf_typ` STRING COMMENT '证书类型',
    `verf_vrfy_rslt` STRING COMMENT '联网核查结果',
    `cib_cd_id` STRING COMMENT '兴业码码串',
    `mkt_bat_id` STRING COMMENT '营销批次ID',
    `mkt_tsk_id` STRING COMMENT '营销任务ID',
    `actv_ser` STRING COMMENT '活动系列',
    `actv_ttl` STRING COMMENT '活动标题',
    `err_lv` STRING COMMENT '错误等级',
    `err_cd` STRING COMMENT '报错编码',
    `err_info` STRING COMMENT '报错信息',
    `err_id` STRING COMMENT '服务端报错返回码',
    `err_method` STRING COMMENT '报错请求方式',
    `err_time` STRING COMMENT '报错时间',
    `err_type` STRING COMMENT '报错类型',
    `err_stack` STRING COMMENT '报错堆栈',
    `err_pcttn_flg` STRING COMMENT '报错感知标志',
    `err_intf_addr` STRING COMMENT '报错接口地址',
    `err_api_lst` STRING COMMENT '报错接口地址列表',
    `info_ttl` STRING COMMENT '内容标题',
    `info_typ` STRING COMMENT '内容类型',
    `comm_fee` STRING COMMENT '手续费',
    `rst_md` STRING COMMENT '重置方式',
    `h5_pg_cust_id` STRING COMMENT 'H5页面用户编号',
    `stp_dur` STRING COMMENT '停留时长',
    `err_src_sys_id` STRING COMMENT '报错来源系统编号',
    `err_src_sys_nm` STRING COMMENT '报错来源系统名称',
    `info_id` STRING COMMENT '资讯/信息编号',
    `load_dur` STRING COMMENT '加载时长',
    `srv_brc_nm` STRING COMMENT '服务网点名称',
    `srv_brc_inst_id` STRING COMMENT '服务网点机构编号',
    `pnt_bal` STRING COMMENT '积分余额',
    `obj_jmp_biz` STRING COMMENT '目标跳转业务',
    `hlp_cntnt` STRING COMMENT '求助内容',
    `sess_id` STRING COMMENT '会话ID',
    `crdntn_mkt_usr_id` STRING COMMENT '协同营销用户编号',
    `actv_ptcp_typ` STRING COMMENT '活动参与类型',
    `eqty_scrty_id` STRING COMMENT '权益券号',
    `eqty_id` STRING COMMENT '权益编号',
    `eqty_nm` STRING COMMENT '权益名称',
    `eqty_typ` STRING COMMENT '权益类型',
    `actv_rls_chnl_id` STRING COMMENT '活动发布渠道编号',
    `jdg_rslt` STRING COMMENT '判断结果',
    `actv_shrt_lnk` STRING COMMENT '活动短链接',
    `pnt_typ` STRING COMMENT '积分类型',
    `cpt_id` STRING COMMENT '组件编号',
    `actv_prz_typ` STRING COMMENT '活动发奖类型',
    `tsk_ttl` STRING COMMENT '任务标题',
    `comm_num` STRING COMMENT '商品编号',
    `cntnt_dtl` STRING COMMENT '内容详情',
    `itgt_rcmd_id` STRING COMMENT '智能推荐编号',
    `qty` STRING COMMENT '数量',
    `kywrd` STRING COMMENT '关键词',
    `strg_rl_inf` STRING COMMENT '策略规则信息',
    `pg_atch_chnl_id` STRING COMMENT '页面归属渠道编码',
    `opn_rgn_cd` STRING COMMENT '开户地区代码',
    `opn_inst_cd` STRING COMMENT '开户机构代码',
    `lst_nm` STRING COMMENT '列表名称',
    `city_nm` STRING COMMENT '城市名称',
    `pg_src_sys_abbr` STRING COMMENT '页面来源系统简称',
    `wc_dt_atch` STRING COMMENT '企业微信数据',
    -- modify by cz 20260303 start
    `unt_popup_tsk_id` STRING COMMENT '统一弹窗任务ID',
    `ast_cat_nm` STRING COMMENT '资产类别名称',
    `aset_fll_prc` STRING COMMENT '资产全价',
    `aset_loc_rgn_nm` STRING COMMENT '资产所在地区',
    `aset_pre_typ` STRING COMMENT '资产展示类型',
    `ent_wc_num` STRING COMMENT '企业微信号',
    `cond_scrn_cntnt` STRING COMMENT '条件筛选内容',
    `exprmnt_info_lst` STRING COMMENT '实验信息列表',
    `pg_plcmnt_chnl_nm` STRING COMMENT '页面投放渠道',
    `rcmd_prd_cd` STRING COMMENT '推荐产品代号',
    `rcmd_prd_typ` STRING COMMENT '推荐产品类型',
    `lst_qry_wrd` STRING COMMENT '上一次输入内容',
    `strg_cntr_ctrl_id` STRING COMMENT '策略中心控件编码',
    `err_msg_typ` STRING COMMENT '报错提示类型'
) COMMENT '兴业生活埋点数据事件表' PARTITIONED BY (`part_dt` STRING COMMENT '分区日期:[yyyyMMdd]') STORED AS PARQUET TBLPROPERTIES ('parquet.compression' = 'SNAPPY');